apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: "18.19.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: redis
      interval: 12h
  valuesFrom:
  - kind: Secret
    name: redis-credentials
    valuesKey: redis-values.yaml
  values:
    architecture: standalone
    master:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: "local-path"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi" 
          cpu: "250m"
    replica:
      replicaCount: 1
      persistence:
        enabled: true
        size: 8Gi
        storageClass: "local-path"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi" 
          cpu: "250m"
    metrics:
      enabled: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"