apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: redis
type: Opaque
data:
  # For testing - replace with SealedSecret in production
  # echo 'auth:\n  enabled: true\n  password: "redispassword123"' | base64 -w 0
  redis-values.yaml: YXV0aDoKICBlbmFibGVkOiB0cnVlCiAgcGFzc3dvcmQ6ICJyZWRpc3Bhc3N3b3JkMTIzIgo=