apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waha-sessions
  namespace: waha
  labels:
    app: waha
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi