apiVersion: v1
kind: Service
metadata:
  name: waha
  namespace: waha
  labels:
    app: waha
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: waha