apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: HelmRelease
      name: loki
    patch: |-
      - op: replace
        path: /spec/values/singleBinary/persistence/size
        value: 5Gi
      - op: replace
        path: /spec/values/singleBinary/resources/limits/memory
        value: 256Mi
      - op: replace
        path: /spec/values/singleBinary/resources/limits/cpu
        value: 100m