# Vaultwarden Deployment
# Bitwarden-compatible password manager
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: selfh-k8s
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/component: security
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: vaultwarden
        image: vaultwarden/server:1.30.3-alpine
        ports:
        - containerPort: 80
          name: http
        env:
        # PostgreSQL connection via DATABASE_URL with secret reference
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vaultwarden-config
              key: database-url
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vaultwarden-config
              key: admin-token
        - name: ROCKET_PORT
          value: "80"
        - name: ROCKET_ADDRESS
          value: "0.0.0.0"
        - name: DOMAIN
          value: "https://vaultwarden.example.com"  # Change this to your domain
        - name: SIGNUPS_ALLOWED
          value: "true"  # Set to false after creating your account
        - name: INVITATIONS_ALLOWED
          value: "true"
        - name: WEB_VAULT_ENABLED
          value: "true"
        - name: WEBSOCKET_ENABLED
          value: "true"
        - name: WEBSOCKET_ADDRESS
          value: "0.0.0.0"
        - name: WEBSOCKET_PORT
          value: "3012"
        - name: SHOW_PASSWORD_HINT
          value: "false"
        - name: LOG_LEVEL
          value: "info"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /alive
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /alive
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vaultwarden-data