apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vaultwarden-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - sealed-secret.yaml
  - db-init-job.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: vaultwarden

labels:
  - pairs:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/component: security
      app.kubernetes.io/part-of: selfh-k8s