# Vaultwarden SealedSecret Template
# Use this template to generate encrypted secrets for new clusters
#
# Instructions:
# 1. Replace the values below with your actual secrets
# 2. Run: echo -n "postgresql://vaultwarden:YOUR_DB_PASSWORD@postgresql.postgresql.svc.cluster.local:5432/vaultwarden" | kubeseal --raw --from-file=/dev/stdin --name vaultwarden-config --namespace vaultwarden
# 3. Run: echo -n "your-admin-token" | kubeseal --raw --from-file=/dev/stdin --name vaultwarden-config --namespace vaultwarden
# 4. Replace the encryptedData values in sealed-secret.yaml
#
# Example commands:
# echo -n "postgresql://vaultwarden:vw-secure-password-2024@postgresql.postgresql.svc.cluster.local:5432/vaultwarden" | kubeseal --raw --from-file=/dev/stdin --name vaultwarden-config --namespace vaultwarden
# echo -n "admin-token-here" | kubeseal --raw --from-file=/dev/stdin --name vaultwarden-config --namespace vaultwarden

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-config
  namespace: vaultwarden
spec:
  encryptedData:
    database-url: REPLACE_WITH_ENCRYPTED_DATABASE_URL
    admin-token: REPLACE_WITH_ENCRYPTED_ADMIN_TOKEN
  template:
    metadata:
      name: vaultwarden-config
      namespace: vaultwarden
    type: Opaque

---
# Plain text template for reference (DO NOT COMMIT TO REPO)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vaultwarden-config
#   namespace: vaultwarden
# type: Opaque
# stringData:
#   database-url: "postgresql://vaultwarden:vw-secure-password-2024@postgresql.postgresql.svc.cluster.local:5432/vaultwarden"  # Full database connection URL
#   admin-token: "your-secure-admin-token-here"   # Admin panel access token