# Grafana Admin Credentials SealedSecret
# Contains encrypted admin password for Grafana
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgA2dkKlPfZ+NTDxKyUGQKJT03UAOVaCcSeJnn7e/6wPhHhKc5+b0Ji31ob1RBsj1sm8uWIeg2+1BCa/Q8IC8nK0zXpk/w6/2xq0AF3pIXtIR/LwrHNjMIPc+TSzcuo4Rw64D8Ri7iwDaEqdeUc6FX/K5rLaWCjg1jZU7JeeqHoVqWwaVeHXEAu/eLRyz+ILnDnL9ZojJKpGEUBlt6opay3ZlvtCH9gZc5VwqX2172o/aaU+jFEZs4F8m3sDXi5r7GaCTf7gBJ4BnLvGvo6RA7GLo9wEGaPxJ+59vaVUkHS4xPMV+hJWNfuyr4MORHfjoMq+ZrrOTfULSAvfIHP/dOm7xG4QHYijwN2I4e2kqbRRi1RJI5HK56k3PdX/Ha09A1eQMfRu30hD7dz91QmMGkgQ0cE5thoAzpYiQjbXySHaSeHvZ7LCNJAfIUElcAXRSbR47LCZ3TRFCEpMtUeztXy7fpoSwWnRakdpKMmQwINR1uaNFV1N9zbRdf71B3bxvW0xBa2Gq+U4fEQCaMihY1LrA07vu3pTH9F5UksjqqdvxlCDReVS41SLRsFyGadq6rPAUzNIss+seXPp347eTdQ1gWJVpXYDx4VaTBWfb8AyVV3PGbOBcvHZpcsHYHiw8QZ0p+EBKy/+tqz3AlWZ8OBukrJEWJ96HE+/9Arpe7dEtIbCKil7/tMPKogFgfAdxpyC/RMUvA==
    admin-password: AgAlMVwqKQ/92SCUidWtVjmj8gasyF+QS/Oqtla7ZqqCRvh80qJ2RCkwW4x10lUXqrk3p/tqKXNmQe55+A8Um4Bc+giJNA/SaUCGZN9pQuKaE3P8XXeghx+8C/tVpHQj8ytzQ19olAoYmaWEwjGS311ZJMuripVn1ugFrWErZdYbu06UicU0nejMaXETI6zDAg8gkPLol/qGTNRhrR9WGBWxIv05GntICxvJYX9qdythBWKTcCB4l39bBAk0i66kPZr9XjIksH17g585iIKNPfld3Q5x2Y7cqixjHAq9h8cgYNluoc8eXVOJmENLQLa3QOamdYz1dbWblFwpsWu8MOUMJctWLy428qhmLMZTU9oJSmS031nqU22ms7yKE7hjpSBVILQZvdsCdnGSjgQgUHV+zudevuCpk8u+R8SbkhKLZHU7TPX/UBOAvUziEqce1EpBMQNXXysENF3qIdL+lrReqLsAa+sYj/5QZIziiM9SKd7vfNOd4m7UMdKIc+s4iZ/yVviPF6hs3J92wzMQWSwO/41CL5d4mxyCNprGqjccBw76E5Z9y37UKjXzK4GOS45lFhw617PtCnF68nPfzbNyOrGTI9Exx07CKxQRVO5VLpycJ/zGppxJnH8D0R1ah/wPt22wWfnE/g0rhYbTCRYl6+rXVlkT/RArPjz4vyfUhErzm5DpQB/kwlI+rWXsujIr2h1dgj9X8g==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque