apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kube-prometheus-stack
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  # Prometheus Operator CRDs and deployment
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.75.2/bundle.yaml
  
  # Helm Repositories
  - prometheus-helm-repository.yaml
  - grafana-helm-repository.yaml
  
  # Helm Releases
  - prometheus-helm-release.yaml
  - grafana-helm-release.yaml
  
  # Dashboards and Configuration
  - custom-dashboard-configmap.yaml
  
  # Native Kubernetes Resources
  - alertmanager.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - servicemonitors.yaml

patches:
  # Move prometheus-operator to monitoring namespace
  - target:
      kind: Deployment
      name: prometheus-operator
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
  - target:
      kind: ServiceAccount
      name: prometheus-operator
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
  - target:
      kind: Service
      name: prometheus-operator
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring

labels:
  - pairs:
      app.kubernetes.io/name: kube-prometheus-stack
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/part-of: selfh-k8s