apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "6.6.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
      interval: 12h
  values:
    deploymentMode: SingleBinary
    
    # Disable other deployment modes
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0
    
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
    
    gateway:
      enabled: false
    
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    
    lokiCanary:
      enabled: false
    
    test:
      enabled: false