apiVersion: v1
kind: Service
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  selector:
    app: netshoot
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  type: ClusterIP