apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: netshoot
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Production - more conservative resource limits
        env:
        - name: ENV
          value: "production"
      # Production security context
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0