apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: netshoot-prod

# Use the base netshoot
resources:
  - ../../base

# Production-specific patches
patchesStrategicMerge:
  - deployment-patch.yaml