apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengist-data
  labels:
    app: opengist
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi