apiVersion: v1
kind: Service
metadata:
  name: opengist
  labels:
    app: opengist
spec:
  selector:
    app: opengist
  ports:
    - name: http
      port: 80
      targetPort: 6157
      protocol: TCP
  type: ClusterIP