# Nextcloud HelmRelease
# Self-hosted file storage and collaboration platform using official Helm chart
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: '4.6.4'
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      interval: 12h
  values:
    # Image configuration
    image:
      repository: nextcloud
      tag: "28-apache"
      pullPolicy: IfNotPresent

    # Nextcloud configuration
    nextcloud:
      host: nextcloud.example.com
      username: admin
      existingSecret:
        enabled: true
        secretName: nextcloud-admin
        usernameKey: username
        passwordKey: password
      mail:
        enabled: false
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://nextcloud.example.com',
            'trusted_proxies' => array(
              0 => '10.0.0.0/8',
              1 => '172.16.0.0/12', 
              2 => '192.168.0.0/16',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );

    # Ingress configuration
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "4G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      tls:
        - secretName: nextcloud-tls
          hosts:
            - nextcloud.example.com

    # Persistence configuration
    persistence:
      enabled: true
      size: 20Gi
      storageClass: local-path
      accessMode: ReadWriteOnce

    # PostgreSQL configuration (external)
    postgresql:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: postgresql.postgresql.svc.cluster.local
      port: 5432
      database: nextcloud
      user: nextcloud
      existingSecret:
        enabled: true 
        secretName: nextcloud-db
        passwordKey: password

    # Redis configuration (disabled for now)
    redis:
      enabled: false

    # Cronjob configuration
    cronjob:
      enabled: true

    # Resource configuration
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

    # Security context - using default from Helm chart
    securityContext: {}
    podSecurityContext: {}

    # Probes configuration
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3

    readinessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    # Service configuration
    service:
      type: ClusterIP
      port: 8080
      loadBalancerIP: ""