apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base GitOps configuration that includes all infrastructure and applications
# This file is used by FluxCD to deploy the entire stack automatically

resources:
  - ../infrastructure/
  - ../apps/