apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "12.12.10"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: postgresql
      interval: 12h
  valuesFrom:
  - kind: Secret
    name: postgresql-credentials
    valuesKey: postgresql-values.yaml
  values:
    primary:
      persistence:
        enabled: true
        size: 10Gi
        storageClass: "local-path"
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "1Gi" 
        cpu: "500m"