apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: postgresql
type: Opaque
data:
  # For testing - replace with SealedSecret in production
  # echo 'auth:\n  postgresPassword: "password123"\n  username: "homelab"\n  password: "password123"\n  database: "homelab"' | base64 -w 0
  postgresql-values.yaml: YXV0aDoKICBwb3N0Z3Jlc1Bhc3N3b3JkOiAicGFzc3dvcmQxMjMiCiAgdXNlcm5hbWU6ICJob21lbGFiIgogIHBhc3N3b3JkOiAicGFzc3dvcmQxMjMiCiAgZGF0YWJhc2U6ICJob21lbGFiIgo=