apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: local-path-provisioner-dev
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: local-path-config
    patch: |-
      - op: replace
        path: /data/config.json
        value: |
          {
            "nodePathMap": [
              {
                "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
                "paths": ["/opt/local-path-provisioner/dev"]
              }
            ]
          }

commonLabels:
  environment: dev