apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: remote-base-example

# Example: Using remote base from apps/productivity/excalidraw
resources:
  - https://github.com/abdullahainun/selfh-k8s/apps/productivity/excalidraw/base

# Override namespace for example
namespace: examples

# Add custom labels
commonLabels:
  example: "true"
  app.kubernetes.io/instance: remote-base-example
