apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: whoami-base

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: whoami
  app.kubernetes.io/component: web-service
