apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activepieces-data
  namespace: activepieces
  labels:
    app: activepieces
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi