apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  interval: 30m
  chart:
    spec:
      chart: mysql
      version: "9.16.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: mysql
      interval: 12h
  valuesFrom:
  - kind: Secret
    name: mysql-credentials
    valuesKey: mysql-values.yaml
  values:
    primary:
      persistence:
        enabled: true
        size: 10Gi
        storageClass: "local-path"
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "1Gi" 
        cpu: "500m"
    metrics:
      enabled: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"