apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: mysql
type: Opaque
data:
  # For testing - replace with SealedSecret in production
  # echo 'auth:\n  rootPassword: "rootpassword123"\n  username: "homelab"\n  password: "password123"\n  database: "homelab"' | base64 -w 0
  mysql-values.yaml: YXV0aDoKICByb290UGFzc3dvcmQ6ICJyb290cGFzc3dvcmQxMjMiCiAgdXNlcm5hbWU6ICJob21lbGFiIgogIHBhc3N3b3JkOiAicGFzc3dvcmQxMjMiCiAgZGF0YWJhc2U6ICJob21lbGFiIgo=