apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    app.kubernetes.io/name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    name: metallb-system
    app.kubernetes.io/name: metallb
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: homelab-apps
  labels:
    name: homelab-apps
    app.kubernetes.io/name: homelab-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins
    app.kubernetes.io/name: jenkins
---
apiVersion: v1
kind: Namespace
metadata:
  name: n8n
  labels:
    name: n8n
    app.kubernetes.io/name: n8n
---
apiVersion: v1
kind: Namespace
metadata:
  name: activepieces
  labels:
    name: activepieces
    app.kubernetes.io/name: activepieces
---
apiVersion: v1
kind: Namespace
metadata:
  name: waha
  labels:
    name: waha
    app.kubernetes.io/name: waha
