apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: local-path-provisioner-prod
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: local-path-config
    patch: |-
      - op: replace
        path: /data/config.json
        value: |
          {
            "nodePathMap": [
              {
                "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
                "paths": ["/opt/local-path-provisioner/prod"]
              }
            ]
          }
  - target:
      kind: Deployment
      name: local-path-provisioner
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

labels:
  - pairs:
      environment: prod