apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkding-credentials
  namespace: linkding
spec:
  encryptedData:
    # Generate encrypted values using:
    # echo -n "admin" | kubeseal --raw --from-file=/dev/stdin --name linkding-credentials --namespace linkding
    username: REPLACE_WITH_ENCRYPTED_USERNAME
    # echo -n "your-secure-password" | kubeseal --raw --from-file=/dev/stdin --name linkding-credentials --namespace linkding  
    password: REPLACE_WITH_ENCRYPTED_PASSWORD
  template:
    metadata:
      name: linkding-credentials
      namespace: linkding
    type: Opaque