apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: HelmRelease
      name: gitea
    patch: |-
      - op: replace
        path: /spec/values/gitea/config/server/DOMAIN
        value: "gitea-dev.yourdomain.com"
      - op: replace
        path: /spec/values/gitea/config/server/SSH_DOMAIN
        value: "gitea-dev.yourdomain.com"
      - op: replace
        path: /spec/values/gitea/config/server/ROOT_URL
        value: "https://gitea-dev.yourdomain.com"
      - op: replace
        path: /spec/values/ingress/hosts/0/host
        value: "gitea-dev.yourdomain.com"
      - op: replace
        path: /spec/values/ingress/tls/0/hosts/0
        value: "gitea-dev.yourdomain.com"
      - op: replace
        path: /spec/values/gitea/admin/email
        value: "admin@gitea-dev.yourdomain.com"
      - op: replace
        path: /spec/values/persistence/size
        value: "10Gi"
      - op: replace
        path: /spec/values/resources/limits/memory
        value: "768Mi"