apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "200m"
    target:
      kind: Deployment
      name: opengist
  - patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "2Gi"
    target:
      kind: PersistentVolumeClaim
      name: opengist-data

commonLabels:
  environment: development