apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gatekeeper-base

# Use official OPA Gatekeeper release manifest as remote base
resources:
  - https://raw.githubusercontent.com/open-policy-agent/gatekeeper/v3.20.0/deploy/gatekeeper.yaml
  - constraint-templates/
  - constraints/

# Common labels for all resources
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/component: policy-engine