apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cert-manager-prod

# Use the base cert-manager
resources:
  - ../../base

# Production-specific patches
patches:
  # Production environment prefers prod issuer
  - target:
      kind: ClusterIssuer
      name: letsencrypt-prod
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1preferred-issuer
        value: "true"

labels:
  - pairs:
      environment: prod