apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: vaultwarden
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: "https://vaultwarden-dev.yourdomain.com"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
  - target:
      kind: Ingress
      name: vaultwarden
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "vaultwarden-dev.yourdomain.com"
      - op: replace
        path: /spec/rules/0/host
        value: "vaultwarden-dev.yourdomain.com"
  - target:
      kind: PersistentVolumeClaim
      name: vaultwarden-data
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: "5Gi"